insert into cards (id,name,type,race,attribute,description,image_url,image_url_small,image_url_cropped) values
(86066372,'Accesscode Talker','Link Monster','Cyberse','DARK','2+ Effect Monsters
Your opponent cannot activate cards or effects in response to this card''s effect activations. If this card is Link Summoned: You can target 1 Link Monster that was used as material for its Link Summon; this card gains ATK equal to that monster''s Link Rating x 1000. You can banish 1 Link Monster from your field or GY; destroy 1 card your opponent controls, also for the rest of t','https://images.ygoprodeck.com/images/cards/86066372.jpg','https://images.ygoprodeck.com/images/cards_small/86066372.jpg','https://images.ygoprodeck.com/images/cards_cropped/86066372.jpg'),
(4280258,'Apollousa, Bow of the Goddess','Link Monster','Fairy','WIND','2+ monsters with different names, except Tokens
You can only control 1 "Apollousa, Bow of the Goddess". The original ATK of this card becomes 800 x the number of Link Materials used for its Link Summon. Once per Chain, when your opponent activates a monster effect (Quick Effect): You can make this card lose exactly 800 ATK, and if you do, negate the activation.','https://images.ygoprodeck.com/images/cards/4280258.jpg','https://images.ygoprodeck.com/images/cards_small/4280258.jpg','https://images.ygoprodeck.com/images/cards_cropped/4280258.jpg'),
(14558127,'Ash Blossom & Joyous Spring','Tuner Monster','Zombie','FIRE','When a card or effect is activated that includes any of these effects (Quick Effect): You can discard this card; negate that effect.
● Add a card from the Deck to the hand.
● Special Summon from the Deck.
● Send a card from the Deck to the GY.
You can only use this effect of "Ash Blossom & Joyous Spring" once per turn.','https://images.ygoprodeck.com/images/cards/14558127.jpg','https://images.ygoprodeck.com/images/cards_small/14558127.jpg','https://images.ygoprodeck.com/images/cards_cropped/14558127.jpg'),
(85106525,'Bonfire','Spell Card','Normal',null,'Add 1 Level 4 or lower Pyro monster from your Deck to your hand. You can only activate 1 "Bonfire" per turn.','https://images.ygoprodeck.com/images/cards/85106525.jpg','https://images.ygoprodeck.com/images/cards_small/85106525.jpg','https://images.ygoprodeck.com/images/cards_cropped/85106525.jpg'),
(24224830,'Called by the Grave','Spell Card','Quick-Play',null,'Target 1 monster in your opponent''s GY; banish it, and if you do, until the end of the next turn, its effects are negated, as well as the activated effects and effects on the field of monsters with the same original name.','https://images.ygoprodeck.com/images/cards/24224830.jpg','https://images.ygoprodeck.com/images/cards_small/24224830.jpg','https://images.ygoprodeck.com/images/cards_cropped/24224830.jpg'),
(58699500,'Cherubini, Ebon Angel of the Burning Abyss','Link Monster','Fairy','DARK','2 Level 3 monsters
Monsters this card points to cannot be destroyed by card effects. If this card would be destroyed by battle or an opponent''s card effect, you can send 1 other card you control to the GY instead. You can send 1 Level 3 monster from your Deck to the GY, then target 1 "Burning Abyss" monster on the field; it gains ATK/DEF equal to the ATK/DEF of the monster sent to the GY, until t','https://images.ygoprodeck.com/images/cards/58699500.jpg','https://images.ygoprodeck.com/images/cards_small/58699500.jpg','https://images.ygoprodeck.com/images/cards_cropped/58699500.jpg'),
(8267140,'Cosmic Cyclone','Spell Card','Quick-Play',null,'Pay 1000 LP, then target 1 Spell/Trap on the field; banish it.','https://images.ygoprodeck.com/images/cards/8267140.jpg','https://images.ygoprodeck.com/images/cards_small/8267140.jpg','https://images.ygoprodeck.com/images/cards_cropped/8267140.jpg'),
(72270339,'Diabellstar the Black Witch','Effect Monster','Spellcaster','DARK','You can Special Summon this card (from your hand) by sending 1 card from your hand or field to the GY. You can only Special Summon "Diabellstar the Black Witch" once per turn this way. You can only use each of the following effects of "Diabellstar the Black Witch" once per turn. If this card is Normal or Special Summoned: You can Set 1 "Sinful Spoils" Spell/Trap directly from your Deck. During you','https://images.ygoprodeck.com/images/cards/72270339.jpg','https://images.ygoprodeck.com/images/cards_small/72270339.jpg','https://images.ygoprodeck.com/images/cards_cropped/72270339.jpg'),
(91800273,'Dimension Shifter','Effect Monster','Spellcaster','DARK','If you have no cards in your GY (Quick Effect): You can send this card from your hand to the GY; until the end of the next turn, any card sent to the GY is banished instead.','https://images.ygoprodeck.com/images/cards/91800273.jpg','https://images.ygoprodeck.com/images/cards_small/91800273.jpg','https://images.ygoprodeck.com/images/cards_cropped/91800273.jpg'),
(94145021,'Droll & Lock Bird','Effect Monster','Spellcaster','WIND','If a card(s) is added from the Main Deck to your opponent''s hand, except during the Draw Phase (Quick Effect): You can send this card from your hand to the GY; for the rest of this turn, cards cannot be added from either player''s Main Deck to the hand.','https://images.ygoprodeck.com/images/cards/94145021.jpg','https://images.ygoprodeck.com/images/cards_small/94145021.jpg','https://images.ygoprodeck.com/images/cards_cropped/94145021.jpg'),
(97268402,'Effect Veiler','Tuner Monster','Spellcaster','LIGHT','During your opponent''s Main Phase (Quick Effect): You can send this card from your hand to the GY, then target 1 Effect Monster your opponent controls; negate the effects of that face-up monster your opponent controls, until the end of this turn.','https://images.ygoprodeck.com/images/cards/97268402.jpg','https://images.ygoprodeck.com/images/cards_small/97268402.jpg','https://images.ygoprodeck.com/images/cards_cropped/97268402.jpg'),
(15693423,'Evenly Matched','Trap Card','Normal',null,'At the end of the Battle Phase, if your opponent controls more cards than you do: You can make your opponent banish cards from their field face-down so they control the same number of cards as you do. If you control no cards, you can activate this card from your hand.','https://images.ygoprodeck.com/images/cards/15693423.jpg','https://images.ygoprodeck.com/images/cards_small/15693423.jpg','https://images.ygoprodeck.com/images/cards_cropped/15693423.jpg'),
(97651498,'Fabled Lurrie','Effect Monster','Fiend','LIGHT','If this card is discarded to the GY: Special Summon it.','https://images.ygoprodeck.com/images/cards/97651498.jpg','https://images.ygoprodeck.com/images/cards_small/97651498.jpg','https://images.ygoprodeck.com/images/cards_cropped/97651498.jpg'),
(60764609,'Fiendsmith Engraver','Effect Monster','Fiend','LIGHT','You can discard this card; add 1 "Fiendsmith" Spell/Trap from your Deck to your hand. You can target 1 "Fiendsmith" Equip Card you control and 1 monster on the field; send them to the GY. If this card is in your GY: You can shuffle 1 other LIGHT Fiend monster from your GY into the Deck/Extra Deck; Special Summon this card. You can only use each effect of "Fiendsmith Engraver" once per turn.','https://images.ygoprodeck.com/images/cards/60764609.jpg','https://images.ygoprodeck.com/images/cards_small/60764609.jpg','https://images.ygoprodeck.com/images/cards_cropped/60764609.jpg'),
(2463794,'Fiendsmith''s Requiem','Link Monster','Fiend','LIGHT','1 LIGHT Fiend monster
You can only Special Summon "Fiendsmith''s Requiem(s)" once per turn. During the Main Phase (Quick Effect): You can Tribute this card; Special Summon 1 "Fiendsmith" monster from your hand or Deck. You can target 1 LIGHT non-Link Fiend monster you control; equip this card from your field or GY to that monster you control as an Equip Spell that gives it 600 ATK. You can only us','https://images.ygoprodeck.com/images/cards/2463794.jpg','https://images.ygoprodeck.com/images/cards_small/2463794.jpg','https://images.ygoprodeck.com/images/cards_cropped/2463794.jpg'),
(98567237,'Fiendsmith''s Tract','Spell Card','Normal',null,'Add 1 LIGHT Fiend monster from your Deck to your hand, then discard 1 card. You can banish this card from your GY; Fusion Summon 1 "Fiendsmith" Fusion Monster from your Extra Deck, using monsters from your hand or field. You can only use each effect of "Fiendsmith''s Tract" once per turn.','https://images.ygoprodeck.com/images/cards/98567237.jpg','https://images.ygoprodeck.com/images/cards_small/98567237.jpg','https://images.ygoprodeck.com/images/cards_cropped/98567237.jpg'),
(59438930,'Ghost Ogre & Snow Rabbit','Tuner Monster','Psychic','LIGHT','When a monster on the field activates its effect, or when a Spell/Trap that is already face-up on the field activates its effect (Quick Effect): You can send this card from your hand or field to the GY; destroy that card on the field. You can only use this effect of "Ghost Ogre & Snow Rabbit" once per turn.','https://images.ygoprodeck.com/images/cards/59438930.jpg','https://images.ygoprodeck.com/images/cards_small/59438930.jpg','https://images.ygoprodeck.com/images/cards_cropped/59438930.jpg'),
(18144506,'Harpie''s Feather Duster','Spell Card','Normal',null,'Destroy all Spell and Trap Cards your opponent controls.','https://images.ygoprodeck.com/images/cards/18144506.jpg','https://images.ygoprodeck.com/images/cards_small/18144506.jpg','https://images.ygoprodeck.com/images/cards_cropped/18144506.jpg'),
(48815792,'Hiita the Fire Charmer, Ablaze','Link Monster','Spellcaster','FIRE','2 monsters, including a FIRE monster
(This card is always treated as a "Familiar-Possessed" card.)
You can target 1 FIRE monster in your opponent''s GY; Special Summon it to your zone this card points to. If this Link Summoned card is destroyed by battle, or is destroyed by an opponent''s card effect while in its owner''s Monster Zone: You can add 1 FIRE monster with 1500 or less DEF from your Deck','https://images.ygoprodeck.com/images/cards/48815792.jpg','https://images.ygoprodeck.com/images/cards_small/48815792.jpg','https://images.ygoprodeck.com/images/cards_cropped/48815792.jpg'),
(65741786,'I:P Masquerena','Link Monster','Cyberse','DARK','2 non-Link Monsters
During your opponent''s Main Phase, you can (Quick Effect): Immediately after this effect resolves, Link Summon 1 Link Monster using materials you control, including this card. You can only use this effect of "I:P Masquerena" once per turn. A Link Monster that used this card as material cannot be destroyed by your opponent''s card effects.','https://images.ygoprodeck.com/images/cards/65741786.jpg','https://images.ygoprodeck.com/images/cards_small/65741786.jpg','https://images.ygoprodeck.com/images/cards_cropped/65741786.jpg'),
(10045474,'Infinite Impermanence','Trap Card','Normal',null,'Target 1 face-up monster your opponent controls; negate its effects (until the end of this turn), then, if this card was Set before activation and is on the field at resolution, for the rest of this turn all other Spell/Trap effects in this column are negated. If you control no cards, you can activate this card from your hand.','https://images.ygoprodeck.com/images/cards/10045474.jpg','https://images.ygoprodeck.com/images/cards_small/10045474.jpg','https://images.ygoprodeck.com/images/cards_cropped/10045474.jpg'),
(38342335,'Knightmare Unicorn','Link Monster','Fiend','DARK','2+ monsters with different names
If this card is Link Summoned: You can discard 1 card, then target 1 card on the field; shuffle it into the Deck, then, if this card was co-linked when this effect was activated, you can draw 1 card. You can only use this effect of "Knightmare Unicorn" once per turn. While any co-linked "Knightmare" monsters are on the field, for your normal draw in your Draw Phas','https://images.ygoprodeck.com/images/cards/38342335.jpg','https://images.ygoprodeck.com/images/cards_small/38342335.jpg','https://images.ygoprodeck.com/images/cards_cropped/38342335.jpg'),
(14532163,'Lightning Storm','Spell Card','Normal',null,'If you control no face-up cards: Activate 1 of these effects;
● Destroy all Attack Position monsters your opponent controls.
● Destroy all Spells and Traps your opponent controls.
You can only activate 1 "Lightning Storm" per turn.','https://images.ygoprodeck.com/images/cards/14532163.jpg','https://images.ygoprodeck.com/images/cards_small/14532163.jpg','https://images.ygoprodeck.com/images/cards_cropped/14532163.jpg'),
(70534340,'Lubellion the Searing Dragon','Fusion Monster','Dragon','LIGHT','1 DARK monster + "Fallen of Albaz"
If this card is Fusion Summoned: You can discard 1 card; Fusion Summon 1 Level 8 or lower Fusion Monster from your Extra Deck, except "Lubellion the Searing Dragon", by shuffling Fusion Materials mentioned on it into the Deck, from your monsters on the field, GY, and/or face-up banished cards. For the rest of this turn, this card cannot attack, also you cannot S','https://images.ygoprodeck.com/images/cards/70534340.jpg','https://images.ygoprodeck.com/images/cards_small/70534340.jpg','https://images.ygoprodeck.com/images/cards_cropped/70534340.jpg'),
(23434538,'Maxx "C"','Effect Monster','Insect','EARTH','During either player''s turn: You can send this card from your hand to the Graveyard; this turn, each time your opponent Special Summons a monster(s), immediately draw 1 card. You can only use 1 "Maxx "C"" per turn.','https://images.ygoprodeck.com/images/cards/23434538.jpg','https://images.ygoprodeck.com/images/cards_small/23434538.jpg','https://images.ygoprodeck.com/images/cards_cropped/23434538.jpg'),
(4779823,'Michael, the Arch-Lightsworn','Synchro Monster','Dragon','LIGHT','1 Tuner + 1 or more non-Tuner LIGHT monsters
Once per turn: You can pay 1000 LP, then target 1 card on the field; banish that target. When this card is destroyed: You can target any number of other "Lightsworn" monsters in your Graveyard; shuffle them into the Deck, and if you do, you gain 300 LP for each returned card. Once per turn, during your End Phase: Send the top 3 cards of your Deck to the','https://images.ygoprodeck.com/images/cards/4779823.jpg','https://images.ygoprodeck.com/images/cards_small/4779823.jpg','https://images.ygoprodeck.com/images/cards_cropped/4779823.jpg'),
(42141493,'Mulcharmy Fuwalos','Effect Monster','Winged Beast','WIND','If you control no cards (Quick Effect): You can discard this card; apply these effects this turn.
● Each time your opponent Special Summons a monster(s) from the Deck and/or Extra Deck, immediately draw 1 card.
● Once, during this End Phase, if the number of cards in your hand is more than the number of cards your opponent controls +6, you must randomly shuffle cards from your hand into the Deck','https://images.ygoprodeck.com/images/cards/42141493.jpg','https://images.ygoprodeck.com/images/cards_small/42141493.jpg','https://images.ygoprodeck.com/images/cards_cropped/42141493.jpg'),
(84192580,'Mulcharmy Purulia','Effect Monster','Aqua','WATER','If you control no cards (Quick Effect): You can discard this card; apply these effects this turn.
● Each time your opponent Normal or Special Summons a monster(s) from the hand, immediately draw 1 card.
● Once, during this End Phase, if the number of cards in your hand is more than the number of cards your opponent controls +6, you must randomly shuffle cards from your hand into the Deck so the ','https://images.ygoprodeck.com/images/cards/84192580.jpg','https://images.ygoprodeck.com/images/cards_small/84192580.jpg','https://images.ygoprodeck.com/images/cards_cropped/84192580.jpg'),
(27204311,'Nibiru, the Primal Being','Effect Monster','Rock','LIGHT','During the Main Phase, if your opponent Normal or Special Summoned 5 or more monsters this turn (Quick Effect): You can Tribute as many face-up monsters on the field as possible, and if you do, Special Summon this card from your hand, then Special Summon 1 "Primal Being Token" (Rock/LIGHT/Level 11/ATK ?/DEF ?) to your opponent''s field. (This Token''s ATK/DEF become the combined original ATK/DEF of ','https://images.ygoprodeck.com/images/cards/27204311.jpg','https://images.ygoprodeck.com/images/cards_small/27204311.jpg','https://images.ygoprodeck.com/images/cards_cropped/27204311.jpg'),
(89023486,'Original Sinful Spoils - Snake-Eye','Spell Card','Normal',null,'Send 1 other face-up card you control to the GY; Special Summon 1 Level 1 FIRE monster from your hand or Deck. You can banish this card from your GY, then target 1 "Snake-Eye" or "Diabellstar" monster in your GY; add 1 Level 1 FIRE monster from your Deck to your hand, then place the targeted monster on the bottom of the Deck. You can only use 1 "Original Sinful Spoils - Snake-Eye" effect per turn,','https://images.ygoprodeck.com/images/cards/89023486.jpg','https://images.ygoprodeck.com/images/cards_small/89023486.jpg','https://images.ygoprodeck.com/images/cards_cropped/89023486.jpg'),
(84211599,'Pot of Prosperity','Spell Card','Normal',null,'Banish 3 or 6 cards of your choice from your Extra Deck, face-down; for the rest of this turn after this card resolves, any damage your opponent takes is halved, also excavate cards from the top of your Deck equal to the number of cards banished, add 1 excavated card to your hand, place the rest on the bottom of your Deck in any order. You can only activate 1 "Pot of Prosperity" per turn. You cann','https://images.ygoprodeck.com/images/cards/84211599.jpg','https://images.ygoprodeck.com/images/cards_small/84211599.jpg','https://images.ygoprodeck.com/images/cards_cropped/84211599.jpg'),
(2772337,'Promethean Princess, Bestower of Flames','Link Monster','Fiend','FIRE','2+ Effect Monsters
You cannot Special Summon monsters, except FIRE monsters. You can only use each of the following effects of "Promethean Princess, Bestower of Flames" once per turn. During your Main Phase: You can Special Summon 1 FIRE monster from your GY. If a monster(s) is Special Summoned to your opponent''s field, while this card is in your GY (except during the Damage Step): You can target','https://images.ygoprodeck.com/images/cards/2772337.jpg','https://images.ygoprodeck.com/images/cards_small/2772337.jpg','https://images.ygoprodeck.com/images/cards_cropped/2772337.jpg'),
(29301450,'S:P Little Knight','Link Monster','Warrior','DARK','2 Effect Monsters
If this card is Link Summoned using a Fusion, Synchro, Xyz, or Link Monster as material: You can target 1 card on the field or in either GY; banish it, also your monsters cannot attack directly this turn. When your opponent activates a card or effect (Quick Effect): You can target 2 face-up monsters on the field, including a monster you control; banish both until the End Phase. ','https://images.ygoprodeck.com/images/cards/29301450.jpg','https://images.ygoprodeck.com/images/cards_small/29301450.jpg','https://images.ygoprodeck.com/images/cards_cropped/29301450.jpg'),
(57134592,'Salamangreat Raging Phoenix','Link Monster','Cyberse','FIRE','2+ FIRE Effect Monsters
If this card is Link Summoned using "Salamangreat Raging Phoenix" as material: You can add 1 "Salamangreat" card from your Deck to your hand. If a face-up FIRE monster(s) you control is destroyed by battle or card effect while this card is in your GY: You can target 1 of those monsters; Special Summon this card, and if you do, this card gains ATK equal to that monster''s AT','https://images.ygoprodeck.com/images/cards/57134592.jpg','https://images.ygoprodeck.com/images/cards_small/57134592.jpg','https://images.ygoprodeck.com/images/cards_cropped/57134592.jpg'),
(9674034,'Snake-Eye Ash','Effect Monster','Pyro','FIRE','If this card is Normal or Special Summoned: You can add 1 Level 1 FIRE monster from your Deck to your hand. You can send 2 face-up cards you control to the GY, including this card; Special Summon 1 "Snake-Eye" monster from your hand or Deck, except "Snake-Eye Ash". You can only use each effect of "Snake-Eye Ash" once per turn.','https://images.ygoprodeck.com/images/cards/9674034.jpg','https://images.ygoprodeck.com/images/cards_small/9674034.jpg','https://images.ygoprodeck.com/images/cards_cropped/9674034.jpg'),
(45663742,'Snake-Eye Oak','Effect Monster','Pyro','FIRE','If this card is Normal or Special Summoned: You can target 1 of your Level 1 FIRE monsters that is banished or in your GY; either add it to your hand or Special Summon it. You can send 2 face-up cards you control to the GY, including this card; Special Summon 1 "Snake-Eye" monster from your hand or Deck, except "Snake-Eye Oak". You can only use each effect of "Snake-Eye Oak" once per turn.','https://images.ygoprodeck.com/images/cards/45663742.jpg','https://images.ygoprodeck.com/images/cards_small/45663742.jpg','https://images.ygoprodeck.com/images/cards_cropped/45663742.jpg'),
(90241276,'Snake-Eyes Poplar','Effect Monster','Pyro','FIRE','If this card is added to your hand, except by drawing it: You can Special Summon this card. If this card is Normal or Special Summoned: You can add 1 "Snake-Eye" Spell/Trap from your Deck to your hand. If this card is sent to the GY: You can target 1 FIRE monster in your GY; place it face-up in its owner''s Spell & Trap Zone as a Continuous Spell. You can only use each effect of "Snake-Eyes Poplar"','https://images.ygoprodeck.com/images/cards/90241276.jpg','https://images.ygoprodeck.com/images/cards_small/90241276.jpg','https://images.ygoprodeck.com/images/cards_cropped/90241276.jpg'),
(32731036,'The Bystial Lubellion','Effect Monster','Dragon','LIGHT','Cannot be Normal Summoned/Set. Must be Special Summoned (from your hand or GY) by Tributing 1 Level 6 or higher DARK Dragon monster. You can only Special Summon "The Bystial Lubellion" once per turn this way. You can send this card from your hand to the GY; add 1 "Bystial" monster from your Deck to your hand, except "The Bystial Lubellion". During your Main Phase: You can place 1 "Branded" Continu','https://images.ygoprodeck.com/images/cards/32731036.jpg','https://images.ygoprodeck.com/images/cards_small/32731036.jpg','https://images.ygoprodeck.com/images/cards_cropped/32731036.jpg'),
(25311006,'Triple Tactics Talent','Spell Card','Normal',null,'If your opponent has activated a monster effect during your Main Phase this turn: Activate 1 of these effects;
● Draw 2 cards.
● Take control of 1 monster your opponent controls until the End Phase.
● Look at your opponent''s hand, and choose 1 card from it to shuffle into the Deck.
You can only activate 1 "Triple Tactics Talent" per turn.','https://images.ygoprodeck.com/images/cards/25311006.jpg','https://images.ygoprodeck.com/images/cards_small/25311006.jpg','https://images.ygoprodeck.com/images/cards_cropped/25311006.jpg'),
(35269904,'Triple Tactics Thrust','Spell Card','Normal',null,'If your opponent has activated a monster effect during this turn: Set 1 Normal Spell/Trap directly from your Deck, except "Triple Tactics Thrust", or if your opponent controls a monster, you can add it to your hand instead. That Set card cannot be activated this turn. You can only activate 1 "Triple Tactics Thrust" per turn.','https://images.ygoprodeck.com/images/cards/35269904.jpg','https://images.ygoprodeck.com/images/cards_small/35269904.jpg','https://images.ygoprodeck.com/images/cards_cropped/35269904.jpg'),
(80845034,'WANTED: Seeker of Sinful Spoils','Spell Card','Quick-Play',null,'Add 1 "Diabellstar" monster from your Deck or GY to your hand. During your Main Phase: You can banish this card from your GY, then target 1 of your "Sinful Spoils" Spells/Traps that is banished or in your GY, except "WANTED: Seeker of Sinful Spoils"; place it on the bottom of the Deck, then draw 1 card. You can only use each effect of "WANTED: Seeker of Sinful Spoils" once per turn.','https://images.ygoprodeck.com/images/cards/80845034.jpg','https://images.ygoprodeck.com/images/cards_small/80845034.jpg','https://images.ygoprodeck.com/images/cards_cropped/80845034.jpg')
on conflict (id) do nothing;
